---
name: Build Fedora Latest

on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]

jobs:
  call-build:
    uses: ./.github/workflows/build.yml
    with:
      os: ubuntu-latest
      container_image: fedora:latest
